import Header from './components/Header'
import { UserProvider } from "./context/user";
import './globals.css'

export const metadata = {
  title: 'Spellbook Companion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen">
        <UserProvider>        
            <Header />
            <main className="h-4/5">
              {children}
            </main>
        </UserProvider>        
      </body>
    </html>
  )
}
