import Header from './components/Header'
import { UserProvider } from "./context/user";
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Spellbook Companion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>        
            <Header />
            <main>
              {children}
            </main>
        </UserProvider>        
      </body>
    </html>
  )
}
